### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by allanzpc** [Saamstep/modmail#11]
**I would like**:
- We can choose the type of status (watch, listen ...)
- We can choose the rotation time of the status (for my part, I would like 3 seconds)
- The bot be adapted with Nodejs V12

> Here is my opinion, I hope that some of these features will be present during the next update.

**Comment by Saamstep** [comment]
Update to ModMail 2.0.0 

**Commit** [`433d521`](https://github.com/Saamstep/modmail/commit/433d521238ce5599def913912f0d741333bd22da)
