### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by DiscordMrPanda** [Saamstep/modmail#13]
Suggestions:
Use comands:
!setcategory (ID)
!setlogchannel (ID)
!reply (Replies to a thread)
!close (time)
!snippets (In thread commands)
!move (Moves to a Category)
!suspend (Suspends a thread(
!unsuspend (Unsuspends a thread)
!block (Blocks a user from using modmail)

**Comment by Saamstep** [comment]
Update to ModMail 2.0.0 

**Commit** [`433d521`](https://github.com/Saamstep/modmail/commit/433d521238ce5599def913912f0d741333bd22da)
