### ISSUE TITLE
Ignoring DMS

### ISSUE THREAD

**Issue by Cyber-Pop** [Saamstep/modmail#18]
`(node:236) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'channels' of undefined
    at hasCategory (/home/runner/modmail/index.js:283:9)
    at CommandoClient.<anonymous> (/home/runner/modmail/index.js:420:9)
    at CommandoClient.emit (events.js:327:22)
    at MessageCreateAction.handle (/home/runner/modmail/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (/home/runner/modmail/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/home/runner/modmail/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (/home/runner/modmail/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (/home/runner/modmail/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
    at WebSocket.onMessage (/home/runner/modmail/node_modules/ws/lib/event-target.js:125:16)
    at WebSocket.emit (events.js:315:20)
(node:236) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:236) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by Saamstep** [comment]
There is currently a bug on the first DM to the bot that results in an error. If you haven’t tried it yet, try DMing the bot again. If that does not work please provide your config file (remove any sensitive information such as the bot token)

**Comment by thecyberpop** [comment]
ok my config file is something like 
`{
  "token": "token",
  "version": 1,
  "prefix": "cyh",
  "debug": false,
  "ownerid": "768398092604801047",
  "status": [
    {
      "type": "PLAYING",
      "msg": "DM me to open a ticket!"
    },
    {
      "type": "WATCHING",
      "msg": "DMs!"
    }
  ],
  "apiKeys": {
    "api": "Your-KEY"
  },
  "modmail": {
    "guild": "768397286430212107",
    "enabled": false,
    "category": "ModMail",
    "rolesAllowed": [],
    "color": 5612998,
    "blockedUsers": [""]
  },
  "messages": {
    "ticketDesc": "This is a private chat with the server administrators/moderators and the user. Bot commands will not be sent, only built in ModMail commands will work. Run the [p]cmds command for more information.",
    "newTicket": "Hello! I have opened up a new ticket for you. One of our staff members will respond back to you shortly. If you need to add anything else to your ticket or send an image you can send it here!",
    "newTicketManual": "Hello! A staff member has created a ticket for you. Please respond back at a convenient time.",
    "closedTicket": "Your ticket has been closed.",
    "blockedUserError": "You are blocked from using modmail.",
    "disabled": "ModMail is currently disabled."
  },
  "snippets": [],
  "role": {
    "mod": "768398092604801047",
    "admin": "768398092604801047"
  },
  "loops": {
    "status": true
  },
  "services": {
    "uptime": false
  },
  "channel": {
    "log": "772457573718818836"
  }
}`

**Comment by thecyberpop** [comment]
Hey there!
Sorry for replying late! And i have tried dming the bot again and again, still the same error.
I have provided my config file as text here
```js
{
  "token":"token",
  "version": 1,
  "prefix": "cyh",
  "debug": false,
  "ownerid": "744142570820730941",
  "status": [
    {
      "type": "WATCHING",
      "msg": "message me for contact"
    },
    {
      "type": "WATCHING",
      "msg": "DMs"
    }
  ],
  "apiKeys": {
    "api": ""
  },
  "modmail": {
    "guild": "747694377706717246",
    "enabled": true,
    "category": "ModMail",
    "rolesAllowed": [],
    "color": 5612998,
    "blockedUsers": [""]
  },
  "messages": {
    "ticketDesc": "This is a private chat with the server administrators/moderators and the user. Bot commands will not be sent, only built in ModMail commands will work. Run the [p]cmds command for more information.",
    "newTicket": "Hello! I have opened up a new ticket for you. One of our staff members will respond back to you shortly. If you need to add anything else to your ticket or send an image you can send it here!",
    "newTicketManual": "Hello! A staff member has created a ticket for you. Please respond back at a convenient time.",
    "closedTicket": "Your ticket has been closed.",
    "blockedUserError": "You are blocked from using modmail.",
    "disabled": "ModMail is currently disabled."
  },
  "snippets": [],
  "role": {
    "mod": "753540798527701043",
    "admin": "753540798527701043"
  },
  "loops": {
    "status": false
  },
  "services": {
    "uptime": false
  },
  "channel": {
    "log": "748897109419229286"
  }
}
```

**Comment by Saamstep** [comment]
everything looks good so far. set status to true if you want the custom messages to be displayed under the bot name. Does you bot have all the correct permissions? 
Manage channels, add reactions, send/manage messages?

**Comment by thecyberpop** [comment]
yes, it has every perms. I'll try again to start it

**Comment by Cyber-Pop** [comment]
anyways, it's working now so i am closing this issue :)
