### ISSUE TITLE
Missing script

### ISSUE THREAD

**Issue by fhwui** [Saamstep/modmail#38]
**Describe the bug**
Missing the start script
**To Reproduce**
1. Start bot

**Expected behavior**
I started the bot and it is saying it's missing teh start script

**Console/Error logs**
 npm start
npm ERR! missing script: start

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-03-02T13_59_24_018Z-debug.log

**System Info**
> repl.it
> 12.16.1
> 6.14.6
> discord.js-commando version 0.12.2
> 2
> missing script: start
**Additional context**

**Comment by Saamstep** [comment]
As documented in the Readme use `node .` or `node index.js` or PM2 to start the bot. https://github.com/Saamstep/modmail#41-setup
