### ISSUE TITLE
Where exactly are the mods added to the ticket?

### ISSUE THREAD

**Issue by Ole-is-live** [Saamstep/modmail#40]

**Comment by Saamstep** [comment]
Hello! The bot creates its own category, you can set the name of said category in the config. Please take a look a the readme.md for more information https://github.com/saamstep/modmail#readme

**Comment by Ole-is-live** [comment]
I wrote the ID of a category in "Category" in the config. Was that wrong?

**Comment by Saamstep** [comment]
Place the name of the category there.

**Comment by Ole-is-live** [comment]
Oh, I'm stupid, so I have to set the permissions in the category and the bot will take over
