### ISSUE TITLE
Help wanted

### ISSUE THREAD

**Issue by Romqxn** [Saamstep/modmail#41]
When I use repl, since I'm not going to host myself until I'm sure it works, when I hit start I get this.
![image](https://user-images.githubusercontent.com/78062132/112153218-700c5880-8bb9-11eb-94a8-110f88e7581f.png)

Import the repo to repl, press start.

For it to not send this error and work.

Already at the top.

**Comment by Saamstep** [comment]
Use the shell and run `node .`

**Comment by Saamstep** [comment]
Can you try reinstalling npm modules?
1. Delete `node_modules` directory
2. Run `npm install --save`

**Comment by Romqxn** [comment]
![image](https://user-images.githubusercontent.com/78062132/113415811-fe3cc780-938d-11eb-95d1-4fd756722c18.png)
![image](https://user-images.githubusercontent.com/78062132/113415825-04cb3f00-938e-11eb-8765-e59c51d323d7.png)
![image](https://user-images.githubusercontent.com/78062132/113415834-08f75c80-938e-11eb-8969-290a817b6b46.png)
Not sure why this won't work.

**Comment by Saamstep** [comment]
Use the role name in the config instead of `MANAGE_GUILD` and `KICK_MEMBERS`
