### ISSUE TITLE
Replit Issue

### ISSUE THREAD

**Issue by JaedonLau** [Saamstep/modmail#59]
While the console is almost done installing packages, it keep saying replit package operation failed.

**Comment by Saamstep** [comment]
Hi, apologies for the extremely late reply, A rewrite was performed and the bot in its new state has not been tested in replit. Support for the older version/code will most likely be dropped as that system is not optimal compared to the new system.

**Comment by JaedonLau** [comment]
> Hi, apologies for the extremely late reply, A rewrite was performed and the bot in its new state has not been tested in replit. Support for the older version/code will most likely be dropped as that system is not optimal compared to the new system.

It's alright, I am always active on Github.
